### ISSUE TITLE
SVELTE Boiler Components & CSS Removal

### ISSUE THREAD

**Issue by kocheck** [kocheck/Lazy-Export#5]
# Overview 
Using the starter components has been great! They have helped this project get up on its feet. This issue is more about me the designer wanting more control over the design system. 

## What Does Success Look Like?
New component structure for the plugin. **Lazy Export** should be using its own components folder with the currently in use buttons and drop-down rewritten. 

**TL;DR** Work out a Figma inspired design system building blocks to build on in the future. 

### Todo
- [x] Clean Componant Code
- [x] Fresh CSS Styles
- [ ] Figma Design file for UI Design
- [x] Fresh documentation to reflect updates
- [x] Fresh documentation to reflect Development updates

**Comment by kocheck** [comment]
First thing, I am going to componatize parts of the code that I want to reuse.

**Comment by kocheck** [comment]
Made some really good progress cleaning up the component code. I now have them imported directly into the repo so I can mutate and slowly move off of the boilerplate template. Mostly because I like to make things difficult. 

I 💯plan on keeping the template Attribution in here, as the code begins to look like the ship`Argo`

**Comment by kocheck** [comment]
This project was a little ambitious honestly. The components have been moved out of the NPM library. 
**Yes, yes I know I shouldn't do that, I am splitting things out to slowly rewrite them. 100% my intention and I would like to understand how all of this is put together.**

The only thing that won't be completed is 
` Figma Design file for UI Design` 
After working through everything I am more concerned about this working correctly than I am how it looks. Kicking that down the line for a UI Refresh later.
