### ISSUE TITLE
UX and Optimization Checklist

### ISSUE THREAD

**Issue by kocheck** [kocheck/Lazy-Export#9]
# Overview 
While re-reading the Figma plugin docs I stumbled across a really great checklist. Making an issue to run through these. 

## Deliverables 
These questions should either be answered or if some amount of work is needed work out answers via fresh issues. 

## Questions 

- [x] If your plugin is only meant to do something if a certain type of nodes is selected, what happens when:
    - [x] The user has nothing selected?
    - [x] ~The wrong type of node selected?~
    - [x] Multiple things selected?
    - [x] A component selected? Are you alright with the change propagating to potentially hundreds of instances?
- [x] ~If your plugin modifies a text layer, what happens if the font for that text layer is missing?~
- [x] ~If your plugin can edit a component, what happens if the component comes from the team library?~
- [x] ~If your plugin needs to load resources over the network, what happens if the user is temporary offline when they run your plugin?~
- [x] If your plugin stays open for a while:
    - [x] ~What happens if the user deletes a node you currently have a reference to?~
    - [x] ~What happens a multiplayer even causes changes in the document?~
- [x] ~If your plugin is concerned with the position of layers, what happens if something is rotated?~
- [x] If your plugin can traverse large parts of the document (e.g. search for a node), what happens if the document is very large?
- [x] If you're using a bundler, have you checked the output size of your plugin? Could you make it smaller (e.g. by running your bundler in release mode)?

**Comment by kocheck** [comment]
>  If your plugin can traverse large parts of the document (e.g. search for a node), what happens if the document is very large?

The plugin seems to perform really well with all functions!

**Comment by kocheck** [comment]
### What happens when,
> The user has nothing selected?

Snack bar pops up asking the user to select a layer

> Multiple things selected?

Loops over all elements applying export settings

> A component selected? Are you alright with the change propagating to potentially hundreds of instances?

Only what is expected, export settings can be applied to all layers.

**Comment by kocheck** [comment]
> If you're using a bundler, have you checked the output size of your plugin? Could you make it smaller (e.g. by running your bundler in release mode)?

This is being handled in Issue #5 right now. The end goal would be to remove the framwork or cut it down to just the bundle code.

**Comment by kocheck** [comment]
Questions answered 🙌
